hello: Pour Poupette
dishes:
    -   name: steak
        meat: true
    -   name: poulet roti
        meat: true
    -   name: agneaux
        meat: true
    -   name: veau
        meat: true
    -   name: oeufs sur le plat
        meat: true
    -   name: cote de porc
        meat: true
    -   name: escalope de dinde sauce champignon
        meat: true
    -   name: tarte / quiche aux legumes + lardon
        meat: true
    -   name: croque monsieur
        meat: true
    -   name: filet mignon de porc
        meat: true
    -   name: salade endive / avocat / chevre chaud / lardon
        meat: true
    -   name: aiguillette de poulet - riz aux champignons
        meat: true
    -   name: pizza
        meat: true
    -   name: pattes carbonara
        meat: true
    -   name: truites
        fish: true
    -   name: salade de quinoa
        vegetarian: true
    -   name: gratin de courgettes
        vegetarian: true
    -   name: dos de cabillaud
        fish: true
        long_preparation: true
    -   name: sole meuniere
        fish: true
        long_preparation: true
    -   name: paupiette de veau
        meat: true
        long_preparation: true
    -   name: travers a la moutarde
        meat: true
        long_preparation: true
    -   name: travers au citron
        meat: true
        long_preparation: true
    -   name: charcuterie
        meat: true
        cold_meat: true
    -   name: cervelas
        meat: true
        cold_meat: true
    -   name: jambonneau
        meat: true
        cold_meat: true
    -   name: hamburger
        meat: true
calendar:
    - name: vendredi
      evening: true
    - name: samedi
      noon: true
      evening: true
    - name: dimanche
      noon: true
      evening: true
    - name: lundi
      evening: true
    - name: mardi
      evening: true
    - name: mercredi
      evening: true
    - name: jeudi
      evening: true
